### ISSUE TITLE
Line Breaks differ between Web and PDF on quotes, colon etc

### ISSUE THREAD

**Issue by tschuehly** [pdfme/pdfme#1115]
### Describe the bug

I have some issues with line breaks currently. The text on my PDFs can be user supplied and I have currently 27 pdfme templates the user can choose from. 

It seems that the web preview correctly handles quotes, colon etc but the PDF renderer does not.
In the Viewer element the line break algo correctly handles the quote as part of the word. In the PDF it handles it as a seperate word and breaks before, which looks very weird

Web Preview:
<img width="526" height="386" alt="Image" src="https://github.com/user-attachments/assets/b132034a-46d4-4916-878e-670a4830cdee" />

Rendered PDF:
<img width="966" height="699" alt="Image" src="https://github.com/user-attachments/assets/f4a072d0-6961-4ced-9fdb-f05cabc7d11c" />

### To Reproduce

You can reproduce the bug on https://pdfme.com/template-design.
Use this [template (37).json](https://github.com/user-attachments/files/21061810/template.37.json) and click on generate pdf.
Doesn't matter if it's a colon, quotation mark, exclamation mark etc.

Web Preview:
<img width="616" height="433" alt="Image" src="https://github.com/user-attachments/assets/f0a34716-8fb0-42a2-877b-30193ddb0245" />

PDF:

<img width="616" height="433" alt="Image" src="https://github.com/user-attachments/assets/cd2a98bc-7cca-49cc-a9e8-811246aa4c97" />

### Expected behavior

The PDF should look the same as in the web preview and handle quotation marks as part of the word.

### Your Environment

```markdown
https://pdfme.com/template-design
```

### Your Error Log

```shell
-
```

**Comment by kyasu1** [comment]
Hi, I am the person who implemented the line breaking code. We need to add line breaking rules and hyphenation for Roman languages, similar to what has been done for Japanese.

You can see the relevant code here:
https://github.com/pdfme/pdfme/blob/663f21229fd532bc3f7ec325ed9fb7036f4fc63a/packages/schemas/src/text/helper.ts#L434-L438

I have implemented such rules (with the help of AI!), and they seem to be working well, as shown below:

<img width="589" height="957" alt="Image" src="https://github.com/user-attachments/assets/ed30cb1e-d2de-4fcf-8a21-d32b25b5ffb6" />

The problem is how to handle other languages. The rules are probably mostly the same for Roman languages, but not for languages like Thai or Arabic. Furthermore, we may want to change the rule for each field. In that case, we would need to modify the schemas to include locale information.

**Comment by kyasu1** [comment]
Hi, I am the person who implemented the line breaking code. We need to add line breaking rules and hyphenation for Roman languages, similar to what has been done for Japanese.

You can see the relevant code here:
https://github.com/pdfme/pdfme/blob/663f21229fd532bc3f7ec325ed9fb7036f4fc63a/packages/schemas/src/text/helper.ts#L434-L438

I have implemented such rules (with the help of AI!). The result shows that they affect the web preview in a better way, and generated PDF is also working well:

<img width="589" height="957" alt="Image" src="https://github.com/user-attachments/assets/9aec579f-4670-4021-a9b2-6d8d96eab779" />

The problem is how to handle other languages. The rules are probably mostly the same for Roman languages, but not for languages like Thai or Arabic. Furthermore, we may want to change the rule for each field. In that case, we would need to modify the schemas to include locale information.

**Comment by kyasu1** [comment]
The scripts in your first example also look good.

<img width="435" height="214" alt="Image" src="https://github.com/user-attachments/assets/fb649fb5-d695-4c54-8944-7d9b186834f2" />

**Comment by tschuehly** [comment]
@kyasu1 Thanks! I think it's the same for all roman languages

**Comment by superiority-claw-agent** [comment]
Fixed in [PDFweave](https://github.com/IDNTEQ/pdfweave) — [PR #4](https://github.com/IDNTEQ/pdfweave/pull/4), commit [`0cd4d454`](https://github.com/IDNTEQ/pdfweave/commit/0cd4d454). Will ship in @pdfweave/* v0.1.1.

Happy to send a PR upstream if a maintainer wants to take it — the diff is isolated. Context on the PDFweave fork: pdfme/pdfme#1468.

— filed by @superiority-claw-agent on behalf of the PDFweave maintainers (IDNTEQ)

**Comment by hand-dot** [comment]
We checked the attached template with @pdfme/generator and @pdfme/schemas 6.1.12 using the built-in default Roboto font family. In the generated PDF, a line ends with `Party-König` and the next starts with `: oder die`, so the punctuation separation still occurs.

We have not completed a side-by-side Viewer comparison for this run. The attached template remains useful for validating the proposed language-aware line-breaking work: the check should cover both PDF output and the web preview, including punctuation at line boundaries.
